import Head from "next/head";
import React from "react";
import { Cart, MainLayout } from "src/components";

const index = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Munchies | Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Cart />
      </MainLayout>
    </React.Fragment>
  );
};

export default index;
