import Head from 'next/head'
import HeroBanner from '../component/heroBanner/HeroBanner'
import Input from '../component/input/Input'
import MainLayoute from '../layoutes/MainLayoute'
import HeroImage from '../public/hero-image.png'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayoute>
          <HeroBanner
            title="Authentic Home food in UK"
            info="What2Eat is a courier service in which authentic home cook food is delivered to a customer."
            bgColor="#0C1712"
            color="#FFFFFF"
            marginTop={200}
            img={HeroImage}
            input={
              <Input
                type="text"
                placeHolder="Search food you love"
                width={398}
                radius={10}
                bg="#FFFFFF"
              />
            }
          />
        </MainLayoute>
      </main>
    </>
  )
}
