import Head from "next/head";

import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { toggleMode } from "../redux/slices/toggleModeSlice";
import { useDispatch, useSelector } from "react-redux";
import { RootStore } from "../redux/app/index";
import MainLayoute from "../layoutes/MainLayoute";
import HeroBanner from "../component/heroBanner/HeroBanner";
export default function Home() {
  const dispatch = useDispatch();
  const { mode } = useSelector((state: RootStore) => state.toggleMode);
  console.log("hello mode from home js", mode);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hello</h1>
        <button onClick={() => dispatch(toggleMode("dark"))}>
          Mode Toggle
        </button>
        <MainLayoute>
          <HeroBanner />
        </MainLayoute>
      </main>
    </>
  );
}
